import {
  H1HeadingMainFontFamily,
  H1HeadingMainFontWeight,
  H1HeadingMainLineHeight,
  H1HeadingMainFontSize,
  H1HeadingMainLetterSpacing,
  H1HeadingMainTextDecoration,
  H1HeadingMainTextCase,
  H2HeadingMainFontFamily,
  H2HeadingMainFontWeight,
  H2HeadingMainLineHeight,
  H2HeadingMainFontSize,
  H2HeadingMainLetterSpacing,
  H2HeadingMainTextDecoration,
  H2HeadingMainTextCase,
  H3HeadingMainFontFamily,
  H3HeadingMainFontWeight,
  H3HeadingMainLineHeight,
  H3HeadingMainFontSize,
  H3HeadingMainLetterSpacing,
  H3HeadingMainTextDecoration,
  H3HeadingMainTextCase,
  H4HeadingMainFontFamily,
  H4HeadingMainFontWeight,
  H4HeadingMainLineHeight,
  H4HeadingMainFontSize,
  H4HeadingMainLetterSpacing,
  H4HeadingMainTextDecoration,
  H4HeadingMainTextCase,
  H5HeadingMainFontFamily,
  H5HeadingMainFontWeight,
  H5HeadingMainLineHeight,
  H5HeadingMainFontSize,
  H5HeadingMainLetterSpacing,
  H5HeadingMainTextDecoration,
  H5HeadingMainTextCase,
  BodyLargeFontFamily,
  BodyLargeFontWeight,
  BodyLargeLineHeight,
  BodyLargeFontSize,
  BodyLargeLetterSpacing,
  BodyLargeTextDecoration,
  BodyLargeTextCase,
  BodyMediumFontFamily,
  BodyMediumFontWeight,
  BodyMediumLineHeight,
  BodyMediumFontSize,
  BodyMediumLetterSpacing,
  BodyMediumTextDecoration,
  BodyMediumTextCase,
  BodySmallFontFamily,
  BodySmallFontWeight,
  BodySmallLineHeight,
  BodySmallFontSize,
  BodySmallLetterSpacing,
  BodySmallTextDecoration,
  BodySmallTextCase,
  CaptionFontFamily,
  CaptionFontWeight,
  CaptionLineHeight,
  CaptionFontSize,
  CaptionLetterSpacing,
  CaptionTextDecoration,
  CaptionTextCase,
  ButtonFontFamily,
  ButtonFontWeight,
  ButtonLineHeight,
  ButtonFontSize,
  ButtonLetterSpacing,
  ButtonTextCase,
  ButtonTextDecoration,
  ButtonSmallFontFamily,
  ButtonSmallFontWeight,
  ButtonSmallLineHeight,
  ButtonSmallFontSize,
  ButtonSmallLetterSpacing,
  ButtonSmallTextCase,
  ButtonSmallTextDecoration,
} from "../../../tokens/js/variables";

const styles: Record<string, React.CSSProperties> = {
  h1: {
    fontFamily: H1HeadingMainFontFamily,
    fontWeight: H1HeadingMainFontWeight,
    lineHeight: H1HeadingMainLineHeight,
    fontSize: H1HeadingMainFontSize,
    letterSpacing: H1HeadingMainLetterSpacing,
    textDecoration: H1HeadingMainTextDecoration,
    textTransform:
      H1HeadingMainTextCase as React.CSSProperties["textTransform"],
  },
  h2: {
    fontFamily: H2HeadingMainFontFamily,
    fontWeight: H2HeadingMainFontWeight,
    lineHeight: H2HeadingMainLineHeight,
    fontSize: H2HeadingMainFontSize,
    letterSpacing: H2HeadingMainLetterSpacing,
    textDecoration: H2HeadingMainTextDecoration,
    textTransform:
      H2HeadingMainTextCase as React.CSSProperties["textTransform"],
  },
  h3: {
    fontFamily: H3HeadingMainFontFamily,
    fontWeight: H3HeadingMainFontWeight,
    lineHeight: H3HeadingMainLineHeight,
    fontSize: H3HeadingMainFontSize,
    letterSpacing: H3HeadingMainLetterSpacing,
    textDecoration: H3HeadingMainTextDecoration,
    textTransform:
      H3HeadingMainTextCase as React.CSSProperties["textTransform"],
  },
  h4: {
    fontFamily: H4HeadingMainFontFamily,
    fontWeight: H4HeadingMainFontWeight,
    lineHeight: H4HeadingMainLineHeight,
    fontSize: H4HeadingMainFontSize,
    letterSpacing: H4HeadingMainLetterSpacing,
    textDecoration: H4HeadingMainTextDecoration,
    textTransform:
      H4HeadingMainTextCase as React.CSSProperties["textTransform"],
  },
  h5: {
    fontFamily: H5HeadingMainFontFamily,
    fontWeight: H5HeadingMainFontWeight,
    lineHeight: H5HeadingMainLineHeight,
    fontSize: H5HeadingMainFontSize,
    letterSpacing: H5HeadingMainLetterSpacing,
    textDecoration: H5HeadingMainTextDecoration,
    textTransform:
      H5HeadingMainTextCase as React.CSSProperties["textTransform"],
  },
  bodyLarge: {
    fontFamily: BodyLargeFontFamily,
    fontWeight: BodyLargeFontWeight,
    lineHeight: BodyLargeLineHeight,
    fontSize: BodyLargeFontSize,
    letterSpacing: BodyLargeLetterSpacing,
    textDecoration: BodyLargeTextDecoration,
    textTransform: BodyLargeTextCase as React.CSSProperties["textTransform"],
  },
  bodyMedium: {
    fontFamily: BodyMediumFontFamily,
    fontWeight: BodyMediumFontWeight,
    lineHeight: BodyMediumLineHeight,
    fontSize: BodyMediumFontSize,
    letterSpacing: BodyMediumLetterSpacing,
    textDecoration: BodyMediumTextDecoration,
    textTransform: BodyMediumTextCase as React.CSSProperties["textTransform"],
  },
  bodySmall: {
    fontFamily: BodySmallFontFamily,
    fontWeight: BodySmallFontWeight,
    lineHeight: BodySmallLineHeight,
    fontSize: BodySmallFontSize,
    letterSpacing: BodySmallLetterSpacing,
    textDecoration: BodySmallTextDecoration,
    textTransform: BodySmallTextCase as React.CSSProperties["textTransform"],
  },
  caption: {
    fontFamily: CaptionFontFamily,
    fontWeight: CaptionFontWeight,
    lineHeight: CaptionLineHeight,
    fontSize: CaptionFontSize,
    letterSpacing: CaptionLetterSpacing,
    textDecoration: CaptionTextDecoration,
    textTransform: CaptionTextCase as React.CSSProperties["textTransform"],
  },
  buttonLarge: {
    fontFamily: ButtonFontFamily,
    fontWeight: ButtonFontWeight,
    lineHeight: ButtonLineHeight,
    fontSize: ButtonFontSize,
    letterSpacing: ButtonLetterSpacing,
    textDecoration: ButtonTextDecoration,
    textTransform: ButtonTextCase as React.CSSProperties["textTransform"],
  },
  buttonSmall: {
    fontFamily: ButtonSmallFontFamily,
    fontWeight: ButtonSmallFontWeight,
    lineHeight: ButtonSmallLineHeight,
    fontSize: ButtonSmallFontSize,
    letterSpacing: ButtonSmallLetterSpacing,
    textDecoration: ButtonSmallTextDecoration,
    textTransform: ButtonSmallTextCase as React.CSSProperties["textTransform"],
  },
};

export default styles;
